---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: web-deploy
 labels:
  app: web
spec:
 replicas: 3
 selector:
  matchLabels:
   mypod: ngpod
  
 template:
  metadata:
   name: pod1
   labels:
    mypod: ngpod
  spec:
   containers: 
   - name: nginxcon1
     image: nginx
     ports:
      - containerPort: 80
