kind: Pod
apiVersion: v1
metadata:
 name: testpod
label:
 env: stage
spec:
 containers:
  - name: con1
    image: ubuntu
    command: ["/bin/bash","-c","while true; do echo Hello-world 01; sleep 5; done"]
  - name: con2
    image: ubuntu
    command: ["/bin/bash","-c","while true; do echo Hello-world 02; sleep 5; done"]
  - name: con3
    image: ubuntu
    command: ["/bin/bash","-c","while true; do echo Hello-world 03; sleep 5; done"]  
 restartPolicy: Never   
