kind: Pod
apiVersion: v1
metadata:
 name: label-pod
 labels:
  env: development
  class: pods
  skill: devops
 annotations:
  description: this is environment variable pod
spec:
 containers:
  - name: con1
    image: ubuntu
    command: ["/bin/bash","-c","while true; do echo Hello-world 01; sleep 5; done"]
