---
kind: Pod
apiVersion: v1
metadata:
 name: empty-vol
spec:
 containers:
  - name: co1
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
     - name: exchange
       mountPath: /tmp/bharath
  - name: co2
    image: centos
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
     - name: exchange
       mountPath: /tmp/thbs     
 volumes : 
  - name : exchange    
    emptyDir : {}
